name: kiwi-tests

on: [push]

jobs:
  kiwi-clang-format:
    runs-on: ubuntu-latest

    steps:
      - name: format
        run: |
          echo ""

  kiwi-compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install gcc-8 g++-8
          pip install gcovr
          mkdir -p build

      - name: compile
        run: |
          git submodule update --init
          cd build
          GCOV=gcov-8 CC=gcc-8 CXX=g++-8 cmake ..
          make enable-debug
          make enable-test
          make -j 4
          make coverage
          bash <(curl -s https://codecov.io/bash)
