name: tests

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install
        run: |
          sudo apt-get update
          sudo apt-get install clang-format-12
          sudo ln -f /usr/bin/clang-format-12 /usr/bin/clang-format

      - name: Format
        run: |
          find src -name '*.cpp'|xargs clang-format --dry-run --Werror --style=file
          find src -name '*.h'|xargs clang-format --dry-run --Werror --style=file

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install gcc-9 g++-9 clang-tidy-12 llvm-12
          sudo ln -f /usr/bin/clang-tidy-12 /usr/bin/clang-tidy
          sudo ln -f /usr/bin/llvm-symbolizer-12 /usr/bin/llvm-symbolizer
          sudo ln -f /usr/bin/gcov-9 /usr/bin/gcov
          pip install gcovr
          mkdir -p build

      - name: Configure
        run: |
          git submodule update --init
          cd build
          GCOV=gcov-9 CC=gcc-9 CXX=g++-9 cmake  ..
          make enable-debug
          make enable-test
        
      - name: Compile
        run: |
          cd build
          make -j $(nproc)

      - name: Test
        run: |
          cd build
          make coverage-xml

      - name: Upload coverage to Codecov
        if: always()
        uses: codecov/codecov-action@v2
