name: tests

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install
        run: |
          sudo apt-get update
          sudo apt-get install clang-format-12
          sudo ln -f /usr/bin/clang-format-12 /usr/bin/clang-format

      - name: Format
        run: |
          find src -name '*.cpp'|xargs clang-format --dry-run --Werror --style=file
          find src -name '*.h'|xargs clang-format --dry-run --Werror --style=file

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install gcc-10 g++-10 clang-tidy-12 llvm-12
          sudo ln -f /usr/bin/clang-tidy-12 /usr/bin/clang-tidy
          sudo ln -f /usr/bin/llvm-symbolizer-12 /usr/bin/llvm-symbolizer
          sudo ln -f /usr/bin/gcov-10 /usr/bin/gcov
          pip install gcovr
          mkdir -p build

      - name: Configure
        run: |
          git submodule update --init
          cd build
          GCOV=gcov-10 CC=gcc-10 CXX=g++-10 cmake  ..
          make enable-debug
          make enable-test
        
      - name: Compile
        run: |
          cd build
          make -j $(nproc)

      - name: Git Clone
        run: |
          git clone --single-branch --branch gh-pages https://${{ secrets.GH_TOKEN }}@github.com/Delaunay/lython.git build/coverage/
          git config --global user.email "Coverage"
          git config --global user.name "Coverage Bot"

      - name: Test
        run: |
          cd build
          make coverage

      - name: Upload coverage to Codecov
        if: always()
        uses: codecov/codecov-action@v2
        with:
          files: build/coverage/coverage.xml

      - name: Deploy
        if: always()
        run: |
          cd build/coverage
          bash ../../scripts/extract_coverage.bash coverage.xml coverage.csv template/badge.svg badge.svg

          git add *.html *.css
          git commit -m "deploy"
          git push https://${{ secrets.GH_TOKEN }}@github.com/Delaunay/lython.git gh-pages
